import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faRobot, faMessage } from '@fortawesome/free-solid-svg-icons'

export default function ReviewSummaryCard({ reviewSummary }: { reviewSummary: string }) {
    if (!reviewSummary || reviewSummary.length === 0) return null

    return (
        <div className="max-w-2xl mx-auto md:mx-0 my-6 p-3 bg-gradient-to-r from-indigo-50 via-white to-pink-50 border-l-4 border-indigo-500 rounded-xl shadow-md animate-fade-in">
            <div className="flex items-center mb-3">
                <FontAwesomeIcon
                    icon={faRobot}
                    className="text-indigo-500 w-6 h-6 mr-2 animate-pulse"
                />
                <h3 className="text-lg font-semibold text-indigo-700">AI Summary</h3>
            </div>
            <p className="text-gray-700 text-base leading-relaxed">{reviewSummary}</p>
            <div className="mt-4 text-right">
                <span className="text-sm text-gray-400 italic">Generated by AI</span>
            </div>
        </div>
    )
}
